exclude: 'settings.py'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v1.4.0-1
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-json
    -   id: check-docstring-first
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: debug-statements
        language_version: python3.7
    -   id: flake8
        language_version: python3.7

